#!/bin/sh
set -e
export RUSTDOCFLAGS=-Dwarnings
cargo fmt -- --check
cargo test -q
cargo clippy --workspace --tests --examples --no-deps
cargo clippy --profile=test
cargo clippy --profile=release --tests --examples --no-deps
cargo doc --workspace --no-deps --document-private-items
